# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('sender', models.CharField(max_length=200, verbose_name='The sender identifier')),
                ('created', models.DateTimeField(blank=True, verbose_name='The transaction creation date')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'managed': True,
            },
        ),
    ]
